name: LottoBot Auto Message

on:
  schedule:
    - cron: '0 2 * * 4'   # 목요일 오전 11시 (UTC 기준 +9시간)
    - cron: '0 13 * * 6'  # 토요일 오후 10시 (UTC 기준 +9시간)
  workflow_dispatch:      # 수동 실행도 가능

jobs:
  run-lotto:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        pip install requests

    - name: Run Lotto Script
      run: |
        if [ "$(date +%u)" -eq 4 ]; then
          echo "목요일 실행: 추천번호 전송"
          python lotto_recommend.py
        elif [ "$(date +%u)" -eq 6 ]; then
          echo "토요일 실행: 결과 분석 및 전송"
          python lotto_result.py
        fi

