name: Lotto Bot

on:
  schedule:
    # 매주 목요일 오전 11시(UTC+9 기준)
    - cron: '0 2 * * 4'
    # 매주 토요일 오후 10시(UTC+9 기준)
    - cron: '0 13 * * 6'
  workflow_dispatch:

jobs:
  run-lotto-bot:
    runs-on: ubuntu-latest

    steps:
    - name: 저장소 불러오기
      uses: actions/checkout@v3

    - name: Python 설치
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: 필요한 모듈 설치
      run: pip install -r requirements.txt

    - name: 로또 추천/결과 전송
      run: |
        if [ "$(date +%u)" -eq 4 ]; then  # 목요일
          python lotto_thursday.py
        elif [ "$(date +%u)" -eq 6 ]; then  # 토요일
          python lotto_result.py
        fi
